### ISSUE TITLE
Learn more link is broken in the HELP Center ("When will the utopian bot upvote my contribution")

### ISSUE THREAD

**Issue by sxiii** [imwatsi/utopian.io-help_center#35]
Here is the link to the article:

https://github.com/imwatsi/utopian.io-help_center/blob/master/faq/when-will-the-utopian-bot-upvote-my-contribution.md

Seems it should head somewhere else?

Please fix. Thanks :+1:

**Comment by imwatsi** [comment]
The link has now been updated to link to the new knowledge base article on Voting Power
